import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import { getServerSession } from "next-auth";
import SessionProvider from "@/providers/SessionProvider";
import LayoutClient from "./layout.client";

const interSans = localFont({
  src: "./fonts/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter-sans",
  weight: "100 900",
});

const permanentSans = localFont({
  src: "./fonts/PermanentMarker-Regular.ttf",
  variable: "--font-permanent marker-sans",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${permanentSans.variable}  antialiased`}
      >
        <SessionProvider session={session}>
          <LayoutClient>{children}</LayoutClient>
        </SessionProvider>
      </body>
    </html>
  );
}
